### ISSUE TITLE
Malformatted traj.xyz

### ISSUE THREAD

**Issue by hoelzerC** [isayevlab/AIMNet2#12]
The `traj.xyz` constructed in the example `docker run -it --rm -v $(pwd):/app/ aimnet-box models/aimnet2_wb97m-d3_ens.jpt input.sdf output.sdf --charge 0 --traj traj.xyz` is malformatted, i.e. not even human-readable.

Would expect a [xyz-file format](https://en.wikipedia.org/wiki/XYZ_file_format).

**Comment by zubatyuk** [comment]
This is the [ASE trajectory format](https://wiki.fysik.dtu.dk/ase/ase/io/trajectory.html). You can convert it to XMOL xyz with `ase convert` tool.

**Comment by hoelzerC** [comment]
Ah, thanks for the clarification. It would be much clearer if the file would be named `ouput.traj` .
