### ISSUE TITLE
Questions about extending AIMnet2 to dimers or large molecules

### ISSUE THREAD

**Issue by binxi0629** [isayevlab/AIMNet2#14]
Hi,

Thank you for your great AI molecular force field model. May I ask several questions about Aimnet2 (or more general, different AIFF approaches for organic molecules).
1. Because the training data set of AIFF usually contain single molecular conformations, when applying Aimnet2 to predict the binding energy between dimers, is there an out-of-distribution problem? Is there anything else we should pay attention to?
2. Is there anything we should pay attention to when applying AIFF (e.g., AIMnet2) to predict the energy of large molecules, such as peptides or proteins (suppose we don't care about computational cost)?

Bests,
Bin

**Comment by isayev** [comment]
Dear @binxi0629, thanks for your interest. Those are very good questions. Generally, as with any ML force field, you need to test. Run a test system and verify with quick DFT calculations. However, in our experience:
1. Geometries are typically very good, but please check the accuracy of interaction energies and atomic forces.
2. Same here; the larger the system probably, the larger the error would be. This specific potential was not trained to any protein data, so you are unlikely to get very good results.

**Comment by binxi0629** [comment]
I like your answers, and thank you for replying.
