### ISSUE TITLE
conda installation failed 

### ISSUE THREAD

**Issue by palazzef** [isayevlab/AIMNet2#28]
Hi,

Thanks for the fantastic project and repo!

I tried to follow the conda instructions and it found some incompatibilities doing this command  `conda install -y -c pyg pytorch-cluster`

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.12.* , which can be installed;
└─ pytorch-cluster is not installable because there are no viable options
   ├─ pytorch-cluster 1.5.9 would require
   │  └─ python >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;
   ├─ pytorch-cluster [1.5.9|1.6.0|1.6.1] would require
   │  └─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
   ├─ pytorch-cluster [1.5.9|1.6.0|1.6.1|1.6.2|1.6.3] would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   ├─ pytorch-cluster [1.5.9|1.6.0|1.6.1|1.6.2|1.6.3] would require
   │  └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported;
   ├─ pytorch-cluster [1.6.0|1.6.1|1.6.2|1.6.3] would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   ├─ pytorch-cluster [1.6.2|1.6.3] would require
   │  └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;
   └─ pytorch-cluster 1.6.3 would require
      └─ pytorch 2.2.* , which conflicts with any installable versions previously reported.

Do you already have a solution to fix this?

Thanks again!
Ciao
Ferri

**Comment by palazzef** [comment]
Thanks I will try!

**Comment by palazzef** [comment]
Hi, It worked but then I got another error still due some incompatibilities:

from aimnet2calc import AIMNet2ASE
  File "conda_env_path/lib/python3.11/site-packages/aimnet2calc-0.0.1-py3.11.egg/aimnet2calc/__init__.py", line 1, in <module>
    from .calculator import AIMNet2Calculator
  File "conda_env_path/lib/python3.11/site-packages/aimnet2calc-0.0.1-py3.11.egg/aimnet2calc/calculator.py", line 4, in <module>
    from aimnet2calc.nblist import nblist_torch_cluster, nblists_torch_pbc
  File "conda_env_path/lib/python3.11/site-packages/aimnet2calc-0.0.1-py3.11.egg/aimnet2calc/nblist.py", line 4, in <module>
    from torch_cluster import radius_graph
  File "conda_env_path/lib/python3.11/site-packages/torch_cluster/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "conda_env_path/lib/python3.11/site-packages/torch/_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
  File "conda_env_path/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^

OSError: conda_env_path/lib/python3.11/site-packages/torch_cluster/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

I tried to install other version of torch_cluster but got the same error.
https://github.com/rusty1s/pytorch_cluster?tab=readme-ov-file


python                    3.11.9          hb806964_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytorch                   2.4.0           py3.11_cuda11.8_cudnn9.1.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torch-cluster             1.6.3+pt23cu118          pypi_0    pypi
torchaudio                2.4.0               py311_cu118    pytorch
torchtriton               3.0.0                     py311    pytorch
torchvision               0.19.0              py311_cu118    pytorch


any idea on how to fix this?
Is it possible to skip the installation of "pytorch-cluster"? 

Thanks a lot in advance

**Comment by palazzef** [comment]
Hi,

using this yml I managed to run aiment2calc:

channels:
  - conda-forge
dependencies:
  - ase
  - autograd
  - dask
  - distributed
  - fabric
  - h5py
  - jinja2
  - joblib
  - matplotlib
  - natsort
  - numpy==1.26.4
  - openbabel
  - pip
  - psutil
  - python=3.11
  - pyyaml
  - rdkit
  - rmsd
  - scikit-learn
  - scipy
  - sympy
  - pytorch=2.2.0
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - pytorch-cluster

**Comment by zubatyuk** [comment]
Great.
Thanks for reporting. I'll try to get away from pytorch-cluster since it causes so many problems with the installation.
