### ISSUE TITLE
geometry 

### ISSUE THREAD

**Issue by DeepDevIA** [isayevlab/AIMNet2#33]
I try to optimize a geometry , and i  have just use the old code of amnet2 to optimize the geometry ,  dont work ..! severely errors. please is there an example to do the optimization of a  geometry   structure.!!!
thanks

**Comment by zubatyuk** [comment]
Hi @DeepDevIA . We provide [ASE](https://wiki.fysik.dtu.dk/ase) and [pysisyphus](https://pysisyphus.readthedocs.io) calculators. Please refer to their documentation and examples regarding geometry optimization. You can also try [Rowan web-based tool](https://rowansci.com).

**Comment by johTin** [comment]
Hi @zubatyuk 
thank you for your response, I appreciate it..

**Comment by DeepDevIA** [comment]
Hi @zubatyuk
thank you for your response, I appreciate it..
