### ISSUE TITLE
Training AIMNet2 on new data

### ISSUE THREAD

**Issue by JSLJ23** [isayevlab/AIMNet2#34]
Hi AIMNet2 authors,

May I know if there's code available for the AIMNet2 model definition and for **training the model from scratch** on different ab-initio data?

Thank you.

**Comment by zubatyuk** [comment]
Check this out: [zubatyuk/aimnet2](https://github.com/zubatyuk/aimnet2)
The documentation is sparse at the moment: [readme.md](https://github.com/zubatyuk/aimnet2/blob/master/aimnet/train/train.md). But the code should work. Please try this out and ask if you have any problems.
