### ISSUE TITLE
Extremely high energies for torsion scan 

### ISSUE THREAD

**Issue by palazzef** [isayevlab/AIMNet2#35]
Hi,

Now that I have a working conda env I'd like to try to obtain the energy profile of a torsion (1D), running a relaxed torsion scan as reported in the aiment2 paper. 

For doing so I have used the example reported here for a 2D torsion scan with ANI:
https://github.com/pablo-arantes/ParametrizANI/blob/main/TorchANI_2D.ipynb

So I firstly generated the confs (rotating only 1 angle) and then I have used the following script to run the relaxed geo opt. Unfortunately the energy that I got are extremely high (up to 0.4 Hartree, ~250 kcal/mol), so I am wondering what I am doing wrong. 
```
import os
from rdkit import Chem
from aimnet2calc import AIMNet2ASE
from rdkit.Chem import AllChem
from ase import Atoms
from ase.io import write
from ase.visualize import view
from ase.io.trajectory import Trajectory
from ase.optimize import BFGS
from ase.constraints import FixInternals, dict2constraint
import numpy as np
from rdkit.Chem import rdMolTransforms
import ase.optimize
import torch

from typing import List
from ase import Atoms
from ase.md.langevin import Langevin
from ase import io
from ase.io import read, write
from ase import units
from ase.constraints import ExternalForce, FixInternals

atom1 = 16
atom2 = 14
atom3 = 8
atom4 = 6

degrees_steps = "15"
workDir = 'my_folder'

opt_tol = 0.005
device = 'cpu'

def mol2arr(mols, device=device):
    coordinates = []
    spices = []
    for mol in mols:
        pos = mol.GetConformer().GetPositions().tolist()
        atomnums = [a.GetAtomicNum() for a in mol.GetAtoms()]
        coordinates.append(pos)
        spices.append(atomnums)
    coordinates = torch.tensor(coordinates,
                               requires_grad=True,
                               device=device)
    species = torch.tensor(spices, device=device)
    return coordinates, species


deg_points = range(-180, (180+int(degrees_steps)), int(degrees_steps))
energies =[]
for i in range(-180, (180+int(degrees_steps)), int(degrees_steps)):
      mol_deg = AllChem.MolFromMolFile ((os.path.join(workDir, f"mol_files/{i}.mol")), removeHs=False)
      mol = io.read(os.path.join(workDir, f"mol_files/{i}.mol"))
      coordinates, species = mol2arr([mol_deg], device)
      tensor1 = coordinates.detach().numpy()
      atoms = Atoms(mol, positions=tensor1[0])
      atoms.center(vacuum=3.0)
      dihedral_indices1 = [int(atom1), int(atom2), int(atom3), int(atom4)]
      dihedral1 = [atoms.get_dihedral(*dihedral_indices1), dihedral_indices1]
      c = FixInternals(dihedrals_deg=[dihedral1])
      atoms.set_constraint(c)
      calculator = AIMNet2ASE('aimnet2')
      atoms.set_calculator(calculator)
      print("Begin minimizing " + f"mol_files/{i}.mol" )
      opt = BFGS(atoms)
      opt.run(fmax=opt_tol)
      write((os.path.join(workDir, f"mol_files/{i}_min.xyz")), format="xyz", images=atoms)
      energy = atoms.get_potential_energy()[0]
      print(atoms.get_potential_energy()[0])
      energies.append(energy)

print(energies)
for i in range(len(energies)):
 print(energies[i]-np.min(energies))
```
 
p.s. regarding where to put `calculator = AIMNet2ASE('aimnet2') ` I also followed the indication of #30 but the results are exactly the same.

**Comment by zubatyuk** [comment]
Hi @palazzef .
It is difficult to say what is going wrong with your calculations. Please provide minimal reproducible example of failed optimization or obviously incorrect AIMNet2 results.

**Comment by palazzef** [comment]
Thanks for the prompt reply.

Do you see any issues in the code that I copy-pasted for relaxed scan with AIMNET2? 

Because the inputs are just mol files (I will share those tomorrow) but I thought that an eventual error should be in this part. 

Thanks again.
Ciao
Ferri

**Comment by palazzef** [comment]
[mol_files.zip](https://github.com/user-attachments/files/16672177/mol_files.zip)

Hi, 
please find attached the input (and output) mol files to be used in the previously attached code. 

By running it I have obtained the following torsion angle profile:
![image](https://github.com/user-attachments/assets/4cfaa182-9f1a-4f41-b033-22890eb31286)
(I have multiplied the Hartree by 627 to obtain kcal/mol)

Thanks a lot in advance.

Ciao,
Ferri

**Comment by zubatyuk** [comment]
> I have multiplied the Hartree by 627 to obtain kcal/mol
