### ISSUE TITLE
Failure to calculate properties of H2

### ISSUE THREAD

**Issue by joegilkes** [isayevlab/AIMNet2#36]
I'm testing out the ASE calculator for AIMNet2 on a variety of small molecules. It seems to work well for most, but I can't make it work for an isolated H2 molecule:

```
2

H      0.38829   -0.00000    0.00000
H     -0.38829    0.00000    0.00000
```

```python
atoms = read("h2_geom.xyz")
calc = AIMNet2ASE("aimnet2", charge=0, mult=1)
atoms.calc = calc
```

When trying `atoms.get_potential_energy()` with this setup, it always returns `-inf`. Similarly, `atoms.get_forces()` returns an array of `nan`. I'm running the model on a GPU, if that matters.

Am I missing something very simple, or is this a bug?

**Comment by zubatyuk** [comment]
Thanks for reporting the bug. Updated models in zubatyuk/aimnet-model-zoo .

**Comment by joegilkes** [comment]
Great, that appears to be working correctly now. Thanks!
