### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by DeepDevIA** [isayevlab/AIMNet2#38]
Hi there..
I would to know why there are 4 files numbered from 0 to 3 for each model knowing that they give different energy and structure for each file..?! how can make differents between.!!

something else, I tried the aimnet2-qr_b97md4_qzvp_2.jpt model it gives nothing I think it has the same problem as describe in:
[https://github.com/isayevlab/AIMNet2/issues/36](url)
Thanks

**Comment by zubatyuk** [comment]
> I would to know why there are 4 files numbered from 0 to 3 for each model knowing that they give different energy and structure for each file..?! how can make differents between.!!

These are models with different initialization of the weights. Statistically, these models give similar results. Disagreement between the models can give an estimate of the prediction confidence.

> something else, I tried the aimnet2-qr_b97md4_qzvp_2.jpt model it gives nothing I think it has the same problem as describe in:
[https://github.com/isayevlab/AIMNet2/issues/36](https://github.com/isayevlab/AIMNet2/issues/url)

The bug was related to long range electrostatics code. aimnet2-qr model should not use explicit electrostatics.

**Comment by DeepDevIA** [comment]
@zubatyuk  thanks for your response

I'm a little confused, for example with the C60 the energy obtained with the different models :
aimnet2_wb97m_0   -2287.6370014600943
aimnet2_wb97m_1   -2287.420225139271
aimnet2_wb97m_2   -2287.90024342262
aimnet2_wb97m_3   -2287.4902789926864
We notice that there is a difference in energies...!
what should I do... should I choose the default model, chosing  the one that gives the lowest energy or let AIMNet2 choose automatically ?!
Thanks..

**Comment by isayev** [comment]
@DeepDevIA, you should probably familiarize yourself with the idea of active learning and the Query by Committee (QBC) approach... e.g., our old paper https://pubs.aip.org/aip/jcp/article/148/24/241733/963478/Less-is-more-Sampling-chemical-space-with-active

This will explain why we use an ensemble of neural nets and how to interpret different energy values.

**Comment by DeepDevIA** [comment]
ok thanks
