### ISSUE TITLE
Periodic Systems

### ISSUE THREAD

**Issue by PythonFZ** [isayevlab/AIMNet2#9]
First of all, this is a great model and I'm enjoying playing around with it.
I set up various different systems and it was able to run a geometry optimization for all of them.
Furthermore, I ran an MD simulation and e.g., in a Box of sulfuric acid and water I could see a proton transfer
![h2so4_water](https://github.com/isayevlab/AIMNet2/assets/46721498/91b577a7-48cf-4327-b14c-a40da49d6c81)

I used the ASECalculator to run the MD simulations. The unwrapped simulation looks good, but when wrapping the particles back into the Box, some particles are too close together. 
Here is an example for a system of water.
![image](https://github.com/isayevlab/AIMNet2/assets/46721498/a6e107f9-a48d-424a-82f5-b211a414b102)

Is there a certain key that has to be set for periodic systems / are periodic systems possible?

**Comment by zubatyuk** [comment]
Hi. At present, PBCs are not supported. The calculator just ignores PBC flag. Therefore after wrapping atoms into the cell, you see overlaps.
PBC-enabled implementation is on the way, expect an update within one or few weeks.

**Comment by mamo248** [comment]
Are there any updates with respect to the PBC-enabled implementation? I love AIMnet2 so far, would really like to test it in MD simulations with bigger systems.
